# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-28 13:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('second', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='User_custom',
        ),
    ]
